### ISSUE TITLE
Develop bulk API queries for larger study areas

### ISSUE THREAD

**Issue by EPajares** [goat-community/mapillary-api#1]
In order to query features for a larger study area: it would be great if the user could pass a study area and queries are performed for a raster of bounding boxes.

**Comment by EPajares** [comment]
We would need a python function doing the following:
- User provides input as shapefile. And scripts is reading the geometry.
- User defines raster size
- Raster is created container the bounding boxes in the needed format for the Mapillary API

**Comment by EPajares** [comment]
@gregoriiv could handle this?

**Comment by gregoriiv** [comment]
Nice! I will manage it.

**Comment by santilinares04** [comment]
Hello guys, I solve the pagination problem and I did a test asking for 120.000 features and it worked (took a while also), about the maximum possible I asked Mapillary and they haven't answered yet.

**Comment by EPajares** [comment]
Great job! I will close this now.
