### ISSUE TITLE
Make scripts more functional

### ISSUE THREAD

**Issue by EPajares** [goat-community/mapillary-api#2]
We should atomize the scripts as much as possible in using functions.

**Comment by EPajares** [comment]
@santiago could you handle this

**Comment by santilinares04** [comment]
Yes, I'm on it!

**Comment by santilinares04** [comment]
@EPajares I've already changed the code so now it is function-based. The functions can either get objects or the detections from the images. 
I also have the scripts to get the images or sequences based on location or owner.
Can you give me access to push the scrips?

**Comment by EPajares** [comment]
Great! Could you do a pull request? It should be able without writing permission to the repository. I can then review the PR and it should be in the repo soon.
