### ISSUE TITLE
add system_type to config.yaml file

### ISSUE THREAD

**Issue by UJehle** [goat-community/mapillary-api#20]
add an option to choose if the code is run in Linux or Windows and automatically adjust of "/" or "\" is used

**Comment by gregoriiv** [comment]
In spite of adding system type to yaml I changed the code with os.path.join() avoiding use '\' or '/'. Now script is cross-platform. The only place where could be conflicts is the path name of shp file of  study area in yaml. But from my point of view it is responsibility of a user to provide correct form of path for his own os.

I can close the issue.

**Comment by UJehle** [comment]
Great! Thanks @gregoriiv
